version: '3.8'

services:
  # Tu aplicación Java
  app:
    build: .
    container_name: bd2-app
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # CORRECCIÓN: Cambiado bd2_database por bd2_tours
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/bd2_tours?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - bd2-network

  # Tu base de datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: bd2-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bd2_tours
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bd2-network
    # El healthcheck asegura que la app de Java espere a que MySQL esté listo para recibir conexiones
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  bd2-network:
    driver: bridge

volumes:
  # Volumen para que los datos de la base de datos no se borren si apagas el contenedor
  mysql_data:
